server:
  address: localhost
  port: 8080
  compression.enabled: true
#  error:
#    include-stacktrace: always
#    path: /error
#    whitelabel.enabled: true
  servlet:
    session:
      cookie:
        name: JSESSIONID
      persistent: true
  tomcat:
    accept-count: 100
    max-connections: 10000
    max-threads: 200
    max-http-form-post-size: 2MB
    max-swallow-size: 2MB
    accesslog:
      enabled: true
      max-days: 1
      directory: ~/fastcampus/logs
      prefix: access_log
      suffix: .log
    connection-timeout: 3s
    resource:
      allow-caching: true
      cache-ttl: 1d

spring:
  mvc:
    static-path-pattern: /static/**
    servlet:
      path: /
  mustache:
    enabled: true
    cache: false
    prefix: classpath:/templates/
    suffix: .mustache
  devtools:
    restart:
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
#    url: "jdbc:h2:~/test"
    url: "jdbc:h2:mem:test"
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: true
    show-sql: true
#    show-sql: false
    hibernate:
      ddl-auto: none
#      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info
#    com.querydsl.sql: DEBUG
#    org.hibernate: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: trace
#    org.hibernate.persister.collection: debug




