spring:
  datasource:
    url: "jdbc:mysql://database-1.czi3jxlxdgwg.ap-northeast-2.rds.amazonaws.com/handson"
    username: handson
    password: asdf1234
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    locations: "classpath:db/migration"

logging:
  level:
    root: info




