insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$QFxnPG6CxQ5PXZOWTpKRQePbBl4HjlU8xog.PVWXpiSoqzMxF6.F.', 'admin');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('ADMIN', @last_insert_id);
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$C.txla/eGkN7LjaAnhO8/uU8kIPW5HzMtUAbklYzaEAZi9Gb6F0Wu', 'user0');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$G0tT46YhsJcFB5NW9Z7VLu3w.g.VaGvWIFXhjlkAJN5FhyWgRdUOa', 'user1');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$m8/Zm4XRr/moiZ36..CnU.lLnlJi3hI2GVeTH2WNGA/h9.SZv3f6q', 'user2');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$HgXykX7nRM1s8XMnONK1Kethha/jhYLUJpF75xL6PZSXM2Zc7hSLm', 'user3');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$hgExlEHgO0dgjNN125nQxew7SuSK//icY8msZCVWB/TnxWOhgEbJG', 'user4');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$OAdc7I3tag7LoVgdNZvPteYPxieisRPV1/uklBMt6yaHdJDyfvQZu', 'user5');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$ie6kbD38NeXzdYu1teXQaOiKBX2L6I8NENgDiAzTWAp98OKj6UMVK', 'user6');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$0p5J76DszbhR3gTe42SnYO3PTaY/hWXkXBLJc.LxF5ilJdj77LUc6', 'user7');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$HcsmJkcMgRhCpINi7rNGd.oDbRysRUc7Ho7z3GCaYJcBk7/v0nUK2', 'user8');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$RtBTmmgy1nXARE7LoK0RA.7JFldnUIcxouf/Ryw3jCr4voKo4eEQm', 'user9');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$Kx/tw7oNpFlcxvCuCHwi7ODbw35ko0I3ewgEx5UJJcLr.WQR.fY.a', 'user10');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$xjy7TqUMnzWM2Hn5QfkdGOu.HdtqMugsPcWOKtlI9wni0OWj9dTBi', 'user11');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$zqOwmYUsS5/bbhch8RmkB.4vfH6WdtuhzfvXMDYd74zpCxCVoJGCK', 'user12');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$0SFhIWl0Kgy8qcasyv/Ph.VHq9TUVGB3Gdt7j3Qxo7wNVGn0VDAoK', 'user13');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$ll6QnCYLUbd.FSzI.nFcLuu87U.B5UitxwQtaNU9yswpzgs61ax8q', 'user14');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$2C.IVK2DXK6424XXnmJJ3.toir4TFGqXbyFc4Jj1p4WOnXuyZJxsy', 'user15');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$DTfm9vy0mx5hjCJK7zLU2.3s4eAhgD9o0ugH.iF9dkslochVjhhpS', 'user16');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$09uhP7ag1TxPuAO4zAf46uh7HwNp0aFZq1G5azHVgXKteo8mqEhQm', 'user17');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$bSqVYuJM3v2HbejNvtyxUO4zaYfz6yUK30iHjrXlfVFv7WmOODuwy', 'user18');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$FlHlQ/oLVaG2qhuH7p4NHej3ORm38./eaTURWe1TqaDCcMOJ1a0ym', 'user19');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$NXerVT062Ci3quA4C6i2F.ywENxBssc8EGwzxlelbDtWPlzba8YBm', 'user20');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$frSxD66sJLm6GZj6AxATjeHXehcnvHNvkHhS3DNKH9leWE.tIqsAa', 'user21');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$jXC/xamZDAFxlwu23AQ9sOPP0O84yIWVzMNFFx7kWutnvJU2xzRRq', 'user22');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$O7FggEQcuQWwqhdsUZ.Lqetk99/29lOuFcqS838R3kKzHtYuMQpu6', 'user23');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$8TP1gG6opS.oWBqPdRpIouq0Cw8lBB77SZW/J1VWfudc4Nxovct06', 'user24');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$k0hK5Lhg4dd8JKSrUhRLoePACUrXBHWEw4Z/RSTFn3euEd.rrsN.C', 'user25');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$JvsuDMgMCAJKWQTj.T570.Yge4sMcHzPNxGGBJ2Y.KKFQB1MmJUPW', 'user26');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$CDlvFBde1xvqiMchQFRQOOrw2/yogBkxdwsPlNdaTsIm5/wXUDDjq', 'user27');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$z6G2ayN2gqtlLRgOBHSx3eOPYbKNf1soCGDFOP6ScFK5eQw1dMQCe', 'user28');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$bpeTGZeoc182/8SrPi3OR.oFsI0LM/5XIBIL72NII1Iqlae6bxIju', 'user29');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$vGIgG7R0mLrNs.NzvlvvVOGxJZVELE1b0WGVu9YfV6o3TyjdWGfJS', 'user30');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$lPN4tt0qkk2HgftjbglLKOAKjNmm0fkkEeJNUZ2j.zsVHcKn5ZWAe', 'user31');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$jhxXX6gqBjx/E.y4od2ALexfv3D7UQuNSWFtRIT4Tovr0brNy5Vhi', 'user32');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$eDXrRU3cGHVFLT/z9xpTQeBKxnAlePbxnmuXqgVv2jx5ooHu0lccW', 'user33');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$h19NECera.yD5/TBYhEQ0eQfUV/lf8msXMTsu10IHRlZyeynP20x2', 'user34');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$ndBM3JW1m3ozvdJB0PufceM/0O070nNvdH78R2RPflA4UPirb24DK', 'user35');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$wQ5gjyGUUBVFuahmsQa.QeBg2e5W/Z0dfNk1w10AKkfOguyd6RcSC', 'user36');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$z.42XRGbNZ61.lGybwoRr.03CqtPxmzfOUrgIrViVdkjvIeb5rYgy', 'user37');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$vrdr.3eXtKbsdaiDsWA17.VYeMGfbeFk/Y1QegFLNR.IYQ5xJ5S6.', 'user38');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$fYZMnbNhgXKUkdDMkOBdsuJEn0lL.mFfqYCrbGM/As3k82SBttska', 'user39');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$UaCBljFDYRRyJ8jH/fc7eexxJqAilDMTp/k8oiunclfmPJE.R04RS', 'user40');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$DLvJQtqFizsm.wZpc4mIrOXvHLTP/yp14TJ1oOhCD8Jiew3Ap7nfa', 'user41');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$FEGbVWNIucjMWPTi7b3LDOuLEW2mZ2b14UqwWSeijNW3UHgkAf1KW', 'user42');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$ZZOFyIQcSl/uKBe6wBIJouHkw.FlT/D98OwPGWo6j6wXpILQuhLtS', 'user43');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$L032qncgqKMK/zUOd0MqiuGk3fbyfPYlu/B/ljMDeo0.oyKGd7rlq', 'user44');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$L3DqUK9MPkfO1PWNhEB0bOi3d9Zuz6sFpl6SRwfN.APzci5Rrdwoe', 'user45');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$pQ55ZHDkQUxF0ulKw21ILOF.4DoJiygL15J59kC66VRWwGeaeRaLm', 'user46');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$IdS5jqcwMIBAaJoYBnHtQeDN1qK9UBfYmrjGatsHfwcf8ELkx7Pyu', 'user47');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$1JWAbEJI9UMLuwhiselI2.u0/LEnCHvpG0Xx1Txsw8K/RgHGUYJYW', 'user48');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$EwHXrCW1hSEHWJNHWUP3UO0RH7SgGcdPm4aJkFPftoKQ3BDmGmux.', 'user49');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$U0eu2DGymQN1m3T9UShL..T8lwEOSQyUNFCI4rTwAn9FEWdN9HsfK', 'user50');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$HyKtOoRGwR0vtoGOAR95pOaxH3cMKSeqKkN2n.WyJ8ZsI.sPI7OPC', 'user51');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$joITApkJhXEyRLryf8SGwO4ukska3f3tXwYy4YW3yX.T68pLpJwBS', 'user52');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$UETC.nw447qCpQ1uGKUasuibIf3kzXZdz/CfMfN8eAAv5bk4NWTxu', 'user53');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$S8Xv0eY1jxn.yVn3AXz6Ue52lAMkDr3ybNxTUyMwMDpFdcRL2.1K.', 'user54');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$NBqypqSSgd5Q/T8YPCIqK.EelwOVIJaKC/48.SBxB5/NqyDFCGwtK', 'user55');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$fZejvCT7rR43Y/tlnWDW7OtV8PtnRudz7.NzhZyJRLbmhX0RUwNw.', 'user56');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$YLquID1RHBY1uTN7Ol1m7eDtEq2M4qG3eFSTcTYWGTOlVI6IQA7Tq', 'user57');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$4adk8veAqWlanG1fCWzfpuy9KBfMGIB0sUM74RU489OIYdpy5qUMy', 'user58');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$ylTE2nGgW.v4/CuILe7vwuFxKxbl5mRChbAfa8dGdmKoTO9sR8YKK', 'user59');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$bw0du2TNKeden.FptD0ZkOctmmFo5YyqMbRKYZ2ie/XpyKXtnFiki', 'user60');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$osRTHRFLaYazHVFxBrnHRuKv.4QlH/itIQrJhgL1EhjmP.QCZDglO', 'user61');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$zUGx4wyEE55ZGTKLb84kS.OU50zlhp..y3BGVNAjd8nSPYakSdU96', 'user62');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$gVf964aTXUP34S2mJYvc2uYmrXlsdCk4IJMCc3CPfXjoPLhf/LVSa', 'user63');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$Wc1EWXuZ1eOdRvM3U8r8xONq7E1Y0rzZ9Q59eEQ/FJENPan/wddJS', 'user64');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$zMLZTDGvurQvyvMoTPLrnejrFkqHJqCNTNls2wNytnlTYeQgUFHky', 'user65');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$9IluqlgKN7Jci9PXu4cTxuh/vaqWLyGKW2Z0P5CeZkpkmrVtRtuLK', 'user66');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$QpxtrGyAya7m0370s8TG9OLQzv3zNMQ0cuXbvC98CwP0KsgJ1KaIO', 'user67');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$4aHzkIq82yGNRNwofq0vzedgx41ZWbtyIW9sLniu2c3Y6XjBlcGw6', 'user68');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$fZ1QZEKAjFtebNfAUkJ39OxtZ0IdaOhYoc6LKjfrj05CIJ.DcEuye', 'user69');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$eAxgxxmGgJV9xifD6ukKUeC3W5EOwNArfv90c9PMpdk58rJq/nKaq', 'user70');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$TuIJ9HAm3.WNrHaRBThigu7YD4u9mJ0yhF7hXtJdO.SLCqEErvxF6', 'user71');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$oCuyUiQ.5/mSXUsAqWWrfeKLsSvIUocVZvrYxB1rReaRrDxJmFuya', 'user72');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$/r61Ecs8/sLfIY1ZNEnIxemnAdn2oap0A6fyVp2qReTX6djexXmUS', 'user73');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$wueWfFXxpOLHeG8RvK9Es.JmzhlQ5OifNeGzjIddA/ExbSZA5j3eu', 'user74');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$LoX4WnkVGDvr0cxYDznf7ur0DS7VFuPW0XwhZ8Tsr0SHvsvcwC/ra', 'user75');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$34ozpPrHDgO3e0a0Jofq7.xeaiOsywhhH0FmrtPkhKyW2Cp1Ee9EO', 'user76');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$jvcMLnqygB3YxZ6TF09tQ.0pUSsHROIQCtOETowp254tfKv0VNxpe', 'user77');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$rg7m2ebYRN104UGiXX8VHuw.nzJNtvY6ThpAPbRBEpHqNEs9XSASq', 'user78');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$BFQ/SdPWGJoeWnFqryLkaOD.iA5n5j4Mv4DxYcuR0Jj4lxO.ttpHy', 'user79');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$Mi9oAgW2yMmDQAl4Ojkxt.uKxuNjPbMSa2kx6kBx2RC6PSBMqUMq2', 'user80');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$/.FuUs5Ed.4Zdc3bbi8Jwub09BgEMFKeBpokbkCChGrYUrudXQcUu', 'user81');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$YPkIZHWuP1CmQVTz40n2fOgzqkGudAMlLPJPJN9b5jxCentt4HaCG', 'user82');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$1N4A7F3zRslIA9XX9uKxietH0PsMl.KkI5HFGXk4n1eSrP7iPwFVW', 'user83');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$Uz6fqeC1BVCPwgQ/IdKVMunXsEQGDBsk.6Burwhns29DnQ6TYiKRq', 'user84');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$Q6NZWYfxEwCjfXJTIc1/nu0K6xP.duRT6vTw3507zrl/YvW1hwAPS', 'user85');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$Yw4pQdGp5km4IXFCq77gfeTpFo6IJczyeEg41wM4WhBFOIIXtZHGC', 'user86');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$BZDqzqH1yQJL9/BhJKuOWu1iZ8M3KpWn2d8lXcqVpRe8O0Emc8aCm', 'user87');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$4uDq9Ikt8VV8BeIDY3Y/2.RI2SoGMhvDFCOyYbuW3nbKxZoL5RoKC', 'user88');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$4Yx8wio2apSvJum8PqIyL.Tmbhmgas6sqMNKKu7513Gs1P8Njih0O', 'user89');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$y8RuTzfBeFvgMyr6hqPMhu9jmRMjJJm08Wy/QHmTqlxwR5y0.bPBq', 'user90');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$pHYJ1b.zlUUpQ2Li.x2lc.FdyinOVwE5d7xcp2xwTBEGfWy3aKLMS', 'user91');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$CXIzbjFOwQ50fzqQ9sGUwOhNcW0RfBye29izts3jNgYsmv5ibx3uG', 'user92');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$knov4ql9hwIJfVUFNiAlT..npzbW2fyEHR4850mTRWOEAoZ7wILem', 'user93');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$GjP5AistOiMiFZVZWUs/Ze14bVv6Od2EPfJ/bN1O/46W3BUlCC5.S', 'user94');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$kwunoYrtWvUHdSgxA1SjAO0SB0cagHVN/J7IOjIUcn2X0xHIZQ3yy', 'user95');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$w0O7K5ZXe4rS4AJc7mHpEuBZhEsizlbX8Aip0LWLg5AP4fXduL/JO', 'user96');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$VV/GWO2benJzBofweEII8u22HtXM/2Hffz9yAe/en91MzWir4TixO', 'user97');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$/2NkZajFC4jKR.t6vYe8eeAASw0WUohj3bFbrW0tFiYGXzdKahWAq', 'user98');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);
insert into user (created_at, age,created_by, updated_at, updated_by, password, username) values (now(), 20, 'system', now(), 'system', '$2a$10$i75Y48IMtdIq3lHNXYG5ku5JyhenGZTVrWsJ7pRIqM4g7VvMw0Ufy', 'user99');
set @last_insert_id = (select last_insert_id());
insert into user_roles (roles, user_id) values ('USER', @last_insert_id);