spring:
  devtools:
    restart:
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:test;MODE=MySQL;"
    username: sa
    password:

  flyway:
    locations: "classpath:db/migration"

logging:
  level:
    root: info
    com.querydsl.sql: DEBUG
    org.hibernate: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.persister.collection: debug




